version: "2"

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./backend/public:/var/www/html/public
    ports:
      - 8000:80
    depends_on:
      - backend
    links:
      - backend
  backend:
    build:
      context: ./docker/backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/var/www/html
    links:
      - db
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=hi-touch
      - DB_USERNAME=root
      - DB_PASSWORD=root
  db:
    build: ./docker/db
    image: mysql:5.7
    volumes:
            - ./docker/db/sql:/docker-entrypoint-initdb.d
            - ./docker/db/.data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hi-touch
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306
